// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cosmos/app/runtime/v1alpha1/module.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cosmos.App.Runtime.V1alpha1 {

  /// <summary>Holder for reflection information generated from cosmos/app/runtime/v1alpha1/module.proto</summary>
  public static partial class ModuleReflection {

    #region Descriptor
    /// <summary>File descriptor for cosmos/app/runtime/v1alpha1/module.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModuleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cihjb3Ntb3MvYXBwL3J1bnRpbWUvdjFhbHBoYTEvbW9kdWxlLnByb3RvEhtj",
            "b3Ntb3MuYXBwLnJ1bnRpbWUudjFhbHBoYTEaIGNvc21vcy9hcHAvdjFhbHBo",
            "YTEvbW9kdWxlLnByb3RvItkCCgZNb2R1bGUSGQoIYXBwX25hbWUYASABKAlS",
            "B2FwcE5hbWUSJQoOYmVnaW5fYmxvY2tlcnMYAiADKAlSDWJlZ2luQmxvY2tl",
            "cnMSIQoMZW5kX2Jsb2NrZXJzGAMgAygJUgtlbmRCbG9ja2VycxIhCgxpbml0",
            "X2dlbmVzaXMYBCADKAlSC2luaXRHZW5lc2lzEiUKDmV4cG9ydF9nZW5lc2lz",
            "GAUgAygJUg1leHBvcnRHZW5lc2lzElsKE292ZXJyaWRlX3N0b3JlX2tleXMY",
            "BiADKAsyKy5jb3Ntb3MuYXBwLnJ1bnRpbWUudjFhbHBoYTEuU3RvcmVLZXlD",
            "b25maWdSEW92ZXJyaWRlU3RvcmVLZXlzOkO6wJbaAT0KJGdpdGh1Yi5jb20v",
            "Y29zbW9zL2Nvc21vcy1zZGsvcnVudGltZRIVChNjb3Ntb3MuYXBwLnYxYWxw",
            "aGExIlMKDlN0b3JlS2V5Q29uZmlnEh8KC21vZHVsZV9uYW1lGAEgASgJUgpt",
            "b2R1bGVOYW1lEiAKDGt2X3N0b3JlX2tleRgCIAEoCVIKa3ZTdG9yZUtleUK9",
            "AQofY29tLmNvc21vcy5hcHAucnVudGltZS52MWFscGhhMUILTW9kdWxlUHJv",
            "dG9QAaICA0NBUqoCG0Nvc21vcy5BcHAuUnVudGltZS5WMWFscGhhMcoCG0Nv",
            "c21vc1xBcHBcUnVudGltZVxWMWFscGhhMeICJ0Nvc21vc1xBcHBcUnVudGlt",
            "ZVxWMWFscGhhMVxHUEJNZXRhZGF0YeoCHkNvc21vczo6QXBwOjpSdW50aW1l",
            "OjpWMWFscGhhMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Cosmos.App.V1alpha1.ModuleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.App.Runtime.V1alpha1.Module), global::Cosmos.App.Runtime.V1alpha1.Module.Parser, new[]{ "AppName", "BeginBlockers", "EndBlockers", "InitGenesis", "ExportGenesis", "OverrideStoreKeys" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.App.Runtime.V1alpha1.StoreKeyConfig), global::Cosmos.App.Runtime.V1alpha1.StoreKeyConfig.Parser, new[]{ "ModuleName", "KvStoreKey" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Module is the config object for the runtime module.
  /// </summary>
  public sealed partial class Module : pb::IMessage<Module>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Module> _parser = new pb::MessageParser<Module>(() => new Module());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Module> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.App.Runtime.V1alpha1.ModuleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Module() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Module(Module other) : this() {
      appName_ = other.appName_;
      beginBlockers_ = other.beginBlockers_.Clone();
      endBlockers_ = other.endBlockers_.Clone();
      initGenesis_ = other.initGenesis_.Clone();
      exportGenesis_ = other.exportGenesis_.Clone();
      overrideStoreKeys_ = other.overrideStoreKeys_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Module Clone() {
      return new Module(this);
    }

    /// <summary>Field number for the "app_name" field.</summary>
    public const int AppNameFieldNumber = 1;
    private string appName_ = "";
    /// <summary>
    /// app_name is the name of the app.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppName {
      get { return appName_; }
      set {
        appName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "begin_blockers" field.</summary>
    public const int BeginBlockersFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_beginBlockers_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> beginBlockers_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// begin_blockers specifies the module names of begin blockers
    /// to call in the order in which they should be called. If this is left empty
    /// no begin blocker will be registered.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> BeginBlockers {
      get { return beginBlockers_; }
    }

    /// <summary>Field number for the "end_blockers" field.</summary>
    public const int EndBlockersFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_endBlockers_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> endBlockers_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// end_blockers specifies the module names of the end blockers
    /// to call in the order in which they should be called. If this is left empty
    /// no end blocker will be registered.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> EndBlockers {
      get { return endBlockers_; }
    }

    /// <summary>Field number for the "init_genesis" field.</summary>
    public const int InitGenesisFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_initGenesis_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> initGenesis_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// init_genesis specifies the module names of init genesis functions
    /// to call in the order in which they should be called. If this is left empty
    /// no init genesis function will be registered.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> InitGenesis {
      get { return initGenesis_; }
    }

    /// <summary>Field number for the "export_genesis" field.</summary>
    public const int ExportGenesisFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_exportGenesis_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> exportGenesis_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// export_genesis specifies the order in which to export module genesis data.
    /// If this is left empty, the init_genesis order will be used for export genesis
    /// if it is specified.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ExportGenesis {
      get { return exportGenesis_; }
    }

    /// <summary>Field number for the "override_store_keys" field.</summary>
    public const int OverrideStoreKeysFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Cosmos.App.Runtime.V1alpha1.StoreKeyConfig> _repeated_overrideStoreKeys_codec
        = pb::FieldCodec.ForMessage(50, global::Cosmos.App.Runtime.V1alpha1.StoreKeyConfig.Parser);
    private readonly pbc::RepeatedField<global::Cosmos.App.Runtime.V1alpha1.StoreKeyConfig> overrideStoreKeys_ = new pbc::RepeatedField<global::Cosmos.App.Runtime.V1alpha1.StoreKeyConfig>();
    /// <summary>
    /// override_store_keys is an optional list of overrides for the module store keys
    /// to be used in keeper construction.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cosmos.App.Runtime.V1alpha1.StoreKeyConfig> OverrideStoreKeys {
      get { return overrideStoreKeys_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Module);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Module other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AppName != other.AppName) return false;
      if(!beginBlockers_.Equals(other.beginBlockers_)) return false;
      if(!endBlockers_.Equals(other.endBlockers_)) return false;
      if(!initGenesis_.Equals(other.initGenesis_)) return false;
      if(!exportGenesis_.Equals(other.exportGenesis_)) return false;
      if(!overrideStoreKeys_.Equals(other.overrideStoreKeys_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AppName.Length != 0) hash ^= AppName.GetHashCode();
      hash ^= beginBlockers_.GetHashCode();
      hash ^= endBlockers_.GetHashCode();
      hash ^= initGenesis_.GetHashCode();
      hash ^= exportGenesis_.GetHashCode();
      hash ^= overrideStoreKeys_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AppName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AppName);
      }
      beginBlockers_.WriteTo(output, _repeated_beginBlockers_codec);
      endBlockers_.WriteTo(output, _repeated_endBlockers_codec);
      initGenesis_.WriteTo(output, _repeated_initGenesis_codec);
      exportGenesis_.WriteTo(output, _repeated_exportGenesis_codec);
      overrideStoreKeys_.WriteTo(output, _repeated_overrideStoreKeys_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AppName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AppName);
      }
      beginBlockers_.WriteTo(ref output, _repeated_beginBlockers_codec);
      endBlockers_.WriteTo(ref output, _repeated_endBlockers_codec);
      initGenesis_.WriteTo(ref output, _repeated_initGenesis_codec);
      exportGenesis_.WriteTo(ref output, _repeated_exportGenesis_codec);
      overrideStoreKeys_.WriteTo(ref output, _repeated_overrideStoreKeys_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AppName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppName);
      }
      size += beginBlockers_.CalculateSize(_repeated_beginBlockers_codec);
      size += endBlockers_.CalculateSize(_repeated_endBlockers_codec);
      size += initGenesis_.CalculateSize(_repeated_initGenesis_codec);
      size += exportGenesis_.CalculateSize(_repeated_exportGenesis_codec);
      size += overrideStoreKeys_.CalculateSize(_repeated_overrideStoreKeys_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Module other) {
      if (other == null) {
        return;
      }
      if (other.AppName.Length != 0) {
        AppName = other.AppName;
      }
      beginBlockers_.Add(other.beginBlockers_);
      endBlockers_.Add(other.endBlockers_);
      initGenesis_.Add(other.initGenesis_);
      exportGenesis_.Add(other.exportGenesis_);
      overrideStoreKeys_.Add(other.overrideStoreKeys_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AppName = input.ReadString();
            break;
          }
          case 18: {
            beginBlockers_.AddEntriesFrom(input, _repeated_beginBlockers_codec);
            break;
          }
          case 26: {
            endBlockers_.AddEntriesFrom(input, _repeated_endBlockers_codec);
            break;
          }
          case 34: {
            initGenesis_.AddEntriesFrom(input, _repeated_initGenesis_codec);
            break;
          }
          case 42: {
            exportGenesis_.AddEntriesFrom(input, _repeated_exportGenesis_codec);
            break;
          }
          case 50: {
            overrideStoreKeys_.AddEntriesFrom(input, _repeated_overrideStoreKeys_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AppName = input.ReadString();
            break;
          }
          case 18: {
            beginBlockers_.AddEntriesFrom(ref input, _repeated_beginBlockers_codec);
            break;
          }
          case 26: {
            endBlockers_.AddEntriesFrom(ref input, _repeated_endBlockers_codec);
            break;
          }
          case 34: {
            initGenesis_.AddEntriesFrom(ref input, _repeated_initGenesis_codec);
            break;
          }
          case 42: {
            exportGenesis_.AddEntriesFrom(ref input, _repeated_exportGenesis_codec);
            break;
          }
          case 50: {
            overrideStoreKeys_.AddEntriesFrom(ref input, _repeated_overrideStoreKeys_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// StoreKeyConfig may be supplied to override the default module store key, which
  /// is the module name.
  /// </summary>
  public sealed partial class StoreKeyConfig : pb::IMessage<StoreKeyConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreKeyConfig> _parser = new pb::MessageParser<StoreKeyConfig>(() => new StoreKeyConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StoreKeyConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.App.Runtime.V1alpha1.ModuleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StoreKeyConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StoreKeyConfig(StoreKeyConfig other) : this() {
      moduleName_ = other.moduleName_;
      kvStoreKey_ = other.kvStoreKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StoreKeyConfig Clone() {
      return new StoreKeyConfig(this);
    }

    /// <summary>Field number for the "module_name" field.</summary>
    public const int ModuleNameFieldNumber = 1;
    private string moduleName_ = "";
    /// <summary>
    /// name of the module to override the store key of
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ModuleName {
      get { return moduleName_; }
      set {
        moduleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "kv_store_key" field.</summary>
    public const int KvStoreKeyFieldNumber = 2;
    private string kvStoreKey_ = "";
    /// <summary>
    /// the kv store key to use instead of the module name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KvStoreKey {
      get { return kvStoreKey_; }
      set {
        kvStoreKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StoreKeyConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StoreKeyConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ModuleName != other.ModuleName) return false;
      if (KvStoreKey != other.KvStoreKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ModuleName.Length != 0) hash ^= ModuleName.GetHashCode();
      if (KvStoreKey.Length != 0) hash ^= KvStoreKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ModuleName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ModuleName);
      }
      if (KvStoreKey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(KvStoreKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ModuleName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ModuleName);
      }
      if (KvStoreKey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(KvStoreKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ModuleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModuleName);
      }
      if (KvStoreKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KvStoreKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StoreKeyConfig other) {
      if (other == null) {
        return;
      }
      if (other.ModuleName.Length != 0) {
        ModuleName = other.ModuleName;
      }
      if (other.KvStoreKey.Length != 0) {
        KvStoreKey = other.KvStoreKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ModuleName = input.ReadString();
            break;
          }
          case 18: {
            KvStoreKey = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ModuleName = input.ReadString();
            break;
          }
          case 18: {
            KvStoreKey = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
